FROM hzcsai_com/k12ai:latest

ARG jupyter_data_dir=/root/.local/share/jupyter
ARG jupyter_conf_dir=/root/.jupyter

RUN APT_INSTALL="apt-get install -y --no-install-recommends" && \
    PIP_INSTALL="pip install -U --no-cache-dir --retries 20 --timeout 120 \
        --trusted-host pypi.tuna.tsinghua.edu.cn \
        --index-url https://pypi.tuna.tsinghua.edu.cn/simple" && \
    apt-get update --fix-missing && \
    DEBIAN_FRONTEND=noninteractive $APT_INSTALL \
        iputils-ping \
        && \
    $PIP_INSTALL \
        ipywidgets \
        jupyter \
        jupyter_contrib_nbextensions \
        jupyter_nbextensions_configurator \
        && \
    jupyter contrib nbextension install --sys-prefix && \
    jupyter nbextensions_configurator enable && \
    mkdir -p ${jupyter_data_dir}/nbextensions && \
    jupyter notebook --generate-config -y

COPY .jupyter_config/jupyter_notebook_config.json ${jupyter_conf_dir}/jupyter_notebook_config.json
COPY .jupyter_config/vim_binding ${jupyter_data_dir}/nbextensions/vim_binding

RUN jupyter nbextension enable vim_binding/vim_binding && \
    jupyter nbextension enable jupyter-js-widgets/extension && \
    jupyter nbextension enable execute_time/ExecuteTime && \
    jupyter nbextension enable tree-filter/index && \
    jupyter nbextension enable snippets_menu/main && \
    jupyter nbextension enable table_beautifier/main && \
    jupyter nbextension enable skip-traceback/main

CMD ["/bin/bash"]
