FROM ubuntu:20.04

LABEL maintainer="hzcsk12@hzcsai.com"

ARG VENDOR
ARG PROJECT
ARG REPOSITORY
ARG TAG
ARG DATE
ARG VERSION
ARG URL
ARG COMMIT
ARG BRANCH

LABEL org.label-schema.schema-version="1.0" \
      org.label-schema.build-date=$DATE \
      org.label-schema.name=$REPOSITORY \
      org.label-schema.description="HZCS K12ai Startup" \
      org.label-schema.url="https://k12.hzcsai.com" \
      org.label-schema.vcs-url=$URL \
      org.label-schema.vcs-ref=$COMMIT \
      org.label-schema.vcs-branch=$BRANCH \
      org.label-schema.vendor=$VENDOR \
      org.label-schema.version=$VERSION

ENV TZ=Asia/Shanghai \
    LANG=C.UTF-8 \
    LC_ALL=C.UTF-8 \
    IS_CONSUL_SERVER=1 \
    PYTHONIOENCODING=utf-8 \
    DEBIAN_FRONTEND=noninteractive \
    APT_INSTALL="apt install -y --no-install-recommends" \
    PIP_INSTALL="python3 -m pip install --no-cache-dir --retries 20 --timeout 120 --trusted-host mirrors.aliyun.com --index-url https://mirrors.aliyun.com/pypi/simple"

RUN sed -i 's/http:\/\/archive\.ubuntu\.com\/ubuntu\//http:\/\/mirrors\.aliyun\.com\/ubuntu\//g' /etc/apt/sources.list \
    && rm -rf /etc/apt/sources.list.d \
    && apt update \
    && $APT_INSTALL ca-certificates d gnupg lsb-release \
    && mkdir -p /etc/apt/keyrings && mkdir -p /etc/apt/sources.list.d \
    && curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg \
    && echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
    $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null \
    && apt update  && $APT_INSTALL docker-ce-cli && apt remove -y gnupg lsb-release

RUN $APT_INSTALL make gcc g++ git unzip zip python3 python3-pip python3-dev \
        libffi-dev iputils-ping net-tools \
        && git config --global --add safe.directory '*'

RUN $PIP_INSTALL python-consul zerorpc psutil GPUtil dictlib pyhocon jsonnet \
        redis flask flask_cors docker minio cos-python-sdk-v5

WORKDIR /hzcsk12

CMD ["/bin/bash"]
