FROM hzcsai_com/k12ai:latest

ARG REPOSITORY

LABEL org.label-schema.name=$REPOSITORY

ARG jupyter_data_dir=/root/.local/share/jupyter
ARG jupyter_conf_dir=/root/.jupyter

COPY external/ipywidgets-8.0.0a0.zip /root/ipywidgets.zip

# opencv-contrib-python 

RUN APT_INSTALL="apt-get install -y --no-install-recommends" && \
    PIP_INSTALL="pip install -U --no-cache-dir --retries 20 --timeout 120 \
        --trusted-host mirrors.intra.didiyun.com \
        --index-url http://mirrors.intra.didiyun.com/pip/simple" && \
    apt-get update --fix-missing && \
    DEBIAN_FRONTEND=noninteractive $APT_INSTALL \
        iputils-ping tree jq net-tools \
        && \
    $PIP_INSTALL \
        crontabs redis flask flask_cors h5py protobuf-compiler \
        pytorch-lightning \
        tfrecord plotly opencv-python imutils \
        minio onnx onnxruntime netron wandb \
        watermark xlrd xgboost

RUN PIP_INSTALL="pip install -U --no-cache-dir --retries 20 --timeout 120 \
        --trusted-host pypi.tuna.tsinghua.edu.cn \
        --index-url https://pypi.tuna.tsinghua.edu.cn/simple" && \
    $PIP_INSTALL \
        /root/ipywidgets.zip \
        detectron2 \
        jupyter \
        jupyter_contrib_nbextensions \
        jupyter_nbextensions_configurator \
        && \
    jupyter contrib nbextension install --sys-prefix && \
    jupyter nbextensions_configurator enable && \
    mkdir -p ${jupyter_data_dir}/nbextensions && \
    mkdir -p ${jupyter_conf_dir}/nbconfig && \
    jupyter notebook --generate-config -y && \
    rm /root/ipywidgets.zip

RUN jupyter nbextension enable vim_binding/vim_binding && \
    jupyter nbextension enable jupyter-js-widgets/extension && \
    jupyter nbextension enable execute_time/ExecuteTime && \
    jupyter nbextension enable snippets_menu/main && \
    jupyter nbextension enable table_beautifier/main && \
    jupyter nbextension enable skip-traceback/main && \
    jupyter nbextension enable toc2/main

COPY .jupyter_config/jupyter_notebook_config.json ${jupyter_conf_dir}/jupyter_notebook_config.json
COPY .jupyter_config/notebook.json ${jupyter_conf_dir}/nbconfig/notebook.json
COPY .jupyter_config/vim_binding ${jupyter_data_dir}/nbextensions/vim_binding

CMD ["/bin/bash"]
