FROM ufoym/deepo:pytorch-py36-cu101

LABEL maintainer="hzcsk12@hzcsai.com"

ARG VENDOR
ARG PROJECT
ARG REPOSITORY
ARG TAG
ARG DATE
ARG VERSION
ARG URL
ARG COMMIT
ARG BRANCH

LABEL org.label-schema.schema-version="1.0" \
      org.label-schema.build-date=$DATE \
      org.label-schema.name=$REPOSITORY \
      org.label-schema.description="HZCS K12ai Base" \
      org.label-schema.url="https://www.hzcsai.com" \
      org.label-schema.vcs-url=$URL \
      org.label-schema.vcs-ref=$COMMIT \
      org.label-schema.vcs-branch=$BRANCH \
      org.label-schema.vendor=$VENDOR \
      org.label-schema.version=$VERSION

LABEL com.nvidia.volumes.needed="nvidia_driver"

ARG CUDA_HOME="/usr/local/cuda"
ENV TZ=Asia/Shanghai \
    LC_ALL=C.UTF-8 \
    LANG=C.UTF-8 \
    PYTHONIOENCODING=utf-8 \
    DEBIAN_FRONTEND=noninteractive \
    CUDA_HOME=${CUDA_HOME} \
    PATH=${CUDA_HOME}/bin/:$PATH \
    LD_LIBRARY_PATH=${CUDA_HOME}/lib:${CUDA_HOME}/lib64:$LD_LIBRARY_PATH \
    NVIDIA_VISIBLE_DEVICES=all \
    NVIDIA_DRIVER_CAPABILITIES=compute,utility

WORKDIR /hzcsk12

# apt install
RUN sed -i 's/http:\/\/archive\.ubuntu\.com\/ubuntu\//http:\/\/mirrors\.intra\.didiyun\.com\/ubuntu\//g' /etc/apt/sources.list
RUN apt-get update --fix-missing
RUN apt-get install -y tzdata bzip2 unzip ca-certificates gcc git curl wget nfs-common htop psmisc \
    libc-dev libevent-dev libglib2.0-0 libsm6 libxext6 libxrender1 libfontconfig1 build-essential \
    net-tools iputils-ping xvfb python3-opengl ffmpeg && \
    rm -rf /var/lib/apt/lists/*  && \
    ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
# RUN apt-get install -y openssh-server openssh-client

# pip install
COPY external/docker/pip/pip.conf /root/.pip/pip.conf
COPY requirements.txt .
RUN pip install --no-cache-dir --timeout 120 -r requirements.txt && rm requirements.txt
RUN mkdir -p external

# install apex
COPY external/apex/apex-master-20200107.zip external/apex-master.zip
RUN pip install --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" external/apex-master.zip

# spacy2.1 with en_core_web_sm-2.1.0
COPY external/en_core_web_sm/en_core_web_sm-2.1.0.tar.gz external/en_core_web_sm.tar.gz
RUN pip install --no-cache-dir external/en_core_web_sm.tar.gz

# install imgaug
COPY external/imgaug/imgaug-master-20190828.zip external/imgaug-master.zip
RUN pip install --no-cache-dir external/imgaug-master.zip

# check install scripts
COPY external/docker/scripts/check_install.sh external/check_install.sh
RUN chmod +x ./external/check_install.sh && ./external/check_install.sh

RUN rm -rf external

# install jupyter
RUN pip install -U jupyter \
        jupyter_contrib_nbextensions \
        jupyter_nbextensions_configurator \
        -i https://pypi.tuna.tsinghua.edu.cn/simple

ARG jupyter_data_dir=/root/.local/share/jupyter
ARG jupyter_conf_dir=/root/.jupyter

RUN jupyter contrib nbextension install --sys-prefix && \
    jupyter nbextensions_configurator enable && \
    mkdir -p ${jupyter_data_dir}/nbextensions && \
    jupyter notebook --generate-config -y
COPY .jupyter_config/jupyter_notebook_config.json ${jupyter_conf_dir}/jupyter_notebook_config.json
COPY .jupyter_config/vim_binding ${jupyter_data_dir}/nbextensions/vim_binding
RUN jupyter nbextension enable vim_binding/vim_binding
