default_language_version:
  python: python3.8

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: end-of-file-fixer

  - repo: local
    hooks:
      - id: black
        name: black
        entry: python -m black
        args: [--skip-string-normalization, --config, ./pyproject.toml]
        language: system
        types: [python]

      - id: flake8
        name: flake8
        entry: python -m flake8
        language: system
        types: [python]
