# This is Conda environment file
# Usage: `conda env update -f environment.yml`

name:
    pl-env

channels:
    - conda-forge
    - pytorch

dependencies:
    #- python=3.7.6
    - pip>=20.0.2
    - numpy>=1.16.4
    - pytorch>=1.3
    - tensorboard>=1.14
    - future>=0.17.1
    - PyYAML>=5.1
    - tqdm>=4.41.0

    # For dev and testing
    - black==19.10b0
    - check-manifest
    - cloudpickle>=1.2
    - coverage
    - codecov>=2.1
    - pytest>=3.0.5
    - pytest-cov
    - pytest-flake8
    - flake8
    - flake8-black
    - autopep8
    - twine==1.13.0
    - pillow<7.0.0
    - scikit-image
    - nltk>=3.3

    # Optional
    - scikit-learn>=0.20.0
    - matplotlib>=3.1.1
    - omegaconf>=2.0.0
    - torchtext>=0.3.1

    - pip:
        - test-tube>=0.7.5
        - mlflow>=1.0.0
        - comet_ml>=1.0.56
        - wandb>=0.8.21
        - neptune-client>=0.4.109
        - horovod>=0.19.1
        - onnxruntime>=1.3.0
