# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vulkan/protos/blocks/arg_layers.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='vulkan/protos/blocks/arg_layers.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n%vulkan/protos/blocks/arg_layers.proto\"\xa0\x01\n\rArgConvParams\x12\x13\n\x0bin_channels\x18\x01 \x01(\t\x12\x14\n\x0cout_channels\x18\x02 \x01(\t\x12\x13\n\x0bkernel_size\x18\x03 \x01(\t\x12\x0e\n\x06stride\x18\x04 \x01(\t\x12\x0f\n\x07padding\x18\x05 \x01(\t\x12\x10\n\x08\x64ilation\x18\x06 \x01(\t\x12\x0e\n\x06groups\x18\x07 \x01(\t\x12\x0c\n\x04\x62ias\x18\x08 \x01(\t\"\x86\x01\n\rArgConvLayers\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07outputs\x18\x02 \x03(\t\x12\x0e\n\x06inputs\x18\x03 \x03(\t\x12$\n\x0clayer_params\x18\x04 \x01(\x0b\x32\x0e.ArgConvParams\x12 \n\nlayer_mode\x18\x05 \x01(\x0e\x32\x0c.ArgConvMode\"%\n\rArgNormParams\x12\x14\n\x0cnum_features\x18\x01 \x01(\t\"\x86\x01\n\rArgNormLayers\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07outputs\x18\x02 \x03(\t\x12\x0e\n\x06inputs\x18\x03 \x03(\t\x12$\n\x0clayer_params\x18\x04 \x01(\x0b\x32\x0e.ArgNormParams\x12 \n\nlayer_mode\x18\x05 \x01(\x0e\x32\x0c.ArgNormMode\"Z\n\tArgLayers\x12\x1e\n\x04\x63onv\x18\x01 \x01(\x0b\x32\x0e.ArgConvLayersH\x00\x12\x1e\n\x04norm\x18\x02 \x01(\x0b\x32\x0e.ArgNormLayersH\x00\x42\r\n\x0blayer_oneof*\x1c\n\x0b\x41rgConvMode\x12\r\n\tARGCONV2D\x10\x00*!\n\x0b\x41rgNormMode\x12\x12\n\x0e\x41RGBATCHNORM2D\x10\x00')
)

_ARGCONVMODE = _descriptor.EnumDescriptor(
  name='ArgConvMode',
  full_name='ArgConvMode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ARGCONV2D', index=0, number=0,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=609,
  serialized_end=637,
)
_sym_db.RegisterEnumDescriptor(_ARGCONVMODE)

ArgConvMode = enum_type_wrapper.EnumTypeWrapper(_ARGCONVMODE)
_ARGNORMMODE = _descriptor.EnumDescriptor(
  name='ArgNormMode',
  full_name='ArgNormMode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ARGBATCHNORM2D', index=0, number=0,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=639,
  serialized_end=672,
)
_sym_db.RegisterEnumDescriptor(_ARGNORMMODE)

ArgNormMode = enum_type_wrapper.EnumTypeWrapper(_ARGNORMMODE)
ARGCONV2D = 0
ARGBATCHNORM2D = 0



_ARGCONVPARAMS = _descriptor.Descriptor(
  name='ArgConvParams',
  full_name='ArgConvParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='in_channels', full_name='ArgConvParams.in_channels', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='out_channels', full_name='ArgConvParams.out_channels', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kernel_size', full_name='ArgConvParams.kernel_size', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stride', full_name='ArgConvParams.stride', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='padding', full_name='ArgConvParams.padding', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dilation', full_name='ArgConvParams.dilation', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='groups', full_name='ArgConvParams.groups', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bias', full_name='ArgConvParams.bias', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=202,
)


_ARGCONVLAYERS = _descriptor.Descriptor(
  name='ArgConvLayers',
  full_name='ArgConvLayers',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ArgConvLayers.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='outputs', full_name='ArgConvLayers.outputs', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='inputs', full_name='ArgConvLayers.inputs', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='layer_params', full_name='ArgConvLayers.layer_params', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='layer_mode', full_name='ArgConvLayers.layer_mode', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=205,
  serialized_end=339,
)


_ARGNORMPARAMS = _descriptor.Descriptor(
  name='ArgNormParams',
  full_name='ArgNormParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_features', full_name='ArgNormParams.num_features', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=341,
  serialized_end=378,
)


_ARGNORMLAYERS = _descriptor.Descriptor(
  name='ArgNormLayers',
  full_name='ArgNormLayers',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ArgNormLayers.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='outputs', full_name='ArgNormLayers.outputs', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='inputs', full_name='ArgNormLayers.inputs', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='layer_params', full_name='ArgNormLayers.layer_params', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='layer_mode', full_name='ArgNormLayers.layer_mode', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=381,
  serialized_end=515,
)


_ARGLAYERS = _descriptor.Descriptor(
  name='ArgLayers',
  full_name='ArgLayers',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='conv', full_name='ArgLayers.conv', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='norm', full_name='ArgLayers.norm', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='layer_oneof', full_name='ArgLayers.layer_oneof',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=517,
  serialized_end=607,
)

_ARGCONVLAYERS.fields_by_name['layer_params'].message_type = _ARGCONVPARAMS
_ARGCONVLAYERS.fields_by_name['layer_mode'].enum_type = _ARGCONVMODE
_ARGNORMLAYERS.fields_by_name['layer_params'].message_type = _ARGNORMPARAMS
_ARGNORMLAYERS.fields_by_name['layer_mode'].enum_type = _ARGNORMMODE
_ARGLAYERS.fields_by_name['conv'].message_type = _ARGCONVLAYERS
_ARGLAYERS.fields_by_name['norm'].message_type = _ARGNORMLAYERS
_ARGLAYERS.oneofs_by_name['layer_oneof'].fields.append(
  _ARGLAYERS.fields_by_name['conv'])
_ARGLAYERS.fields_by_name['conv'].containing_oneof = _ARGLAYERS.oneofs_by_name['layer_oneof']
_ARGLAYERS.oneofs_by_name['layer_oneof'].fields.append(
  _ARGLAYERS.fields_by_name['norm'])
_ARGLAYERS.fields_by_name['norm'].containing_oneof = _ARGLAYERS.oneofs_by_name['layer_oneof']
DESCRIPTOR.message_types_by_name['ArgConvParams'] = _ARGCONVPARAMS
DESCRIPTOR.message_types_by_name['ArgConvLayers'] = _ARGCONVLAYERS
DESCRIPTOR.message_types_by_name['ArgNormParams'] = _ARGNORMPARAMS
DESCRIPTOR.message_types_by_name['ArgNormLayers'] = _ARGNORMLAYERS
DESCRIPTOR.message_types_by_name['ArgLayers'] = _ARGLAYERS
DESCRIPTOR.enum_types_by_name['ArgConvMode'] = _ARGCONVMODE
DESCRIPTOR.enum_types_by_name['ArgNormMode'] = _ARGNORMMODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ArgConvParams = _reflection.GeneratedProtocolMessageType('ArgConvParams', (_message.Message,), dict(
  DESCRIPTOR = _ARGCONVPARAMS,
  __module__ = 'vulkan.protos.blocks.arg_layers_pb2'
  # @@protoc_insertion_point(class_scope:ArgConvParams)
  ))
_sym_db.RegisterMessage(ArgConvParams)

ArgConvLayers = _reflection.GeneratedProtocolMessageType('ArgConvLayers', (_message.Message,), dict(
  DESCRIPTOR = _ARGCONVLAYERS,
  __module__ = 'vulkan.protos.blocks.arg_layers_pb2'
  # @@protoc_insertion_point(class_scope:ArgConvLayers)
  ))
_sym_db.RegisterMessage(ArgConvLayers)

ArgNormParams = _reflection.GeneratedProtocolMessageType('ArgNormParams', (_message.Message,), dict(
  DESCRIPTOR = _ARGNORMPARAMS,
  __module__ = 'vulkan.protos.blocks.arg_layers_pb2'
  # @@protoc_insertion_point(class_scope:ArgNormParams)
  ))
_sym_db.RegisterMessage(ArgNormParams)

ArgNormLayers = _reflection.GeneratedProtocolMessageType('ArgNormLayers', (_message.Message,), dict(
  DESCRIPTOR = _ARGNORMLAYERS,
  __module__ = 'vulkan.protos.blocks.arg_layers_pb2'
  # @@protoc_insertion_point(class_scope:ArgNormLayers)
  ))
_sym_db.RegisterMessage(ArgNormLayers)

ArgLayers = _reflection.GeneratedProtocolMessageType('ArgLayers', (_message.Message,), dict(
  DESCRIPTOR = _ARGLAYERS,
  __module__ = 'vulkan.protos.blocks.arg_layers_pb2'
  # @@protoc_insertion_point(class_scope:ArgLayers)
  ))
_sym_db.RegisterMessage(ArgLayers)


# @@protoc_insertion_point(module_scope)
