# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vulkan/protos/layers/activations.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='vulkan/protos/layers/activations.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n&vulkan/protos/layers/activations.proto\"\xf0\x01\n\x11\x61\x63tivation_params\x12\x0f\n\x07inplace\x18\x01 \x01(\t\x12\r\n\x05\x61lpha\x18\x02 \x01(\t\x12\r\n\x05lambd\x18\x03 \x01(\t\x12\x16\n\x0enum_parameters\x18\x04 \x01(\t\x12\x0f\n\x07min_val\x18\x05 \x01(\t\x12\x0f\n\x07max_val\x18\x06 \x01(\t\x12\x16\n\x0enegative_slope\x18\x07 \x01(\t\x12\r\n\x05lower\x18\x08 \x01(\t\x12\r\n\x05upper\x18\t \x01(\t\x12\x0c\n\x04\x62\x65ta\x18\n \x01(\t\x12\x11\n\tthreshold\x18\x0b \x01(\t\x12\r\n\x05value\x18\x0c \x01(\t\x12\x0c\n\x04init\x18\r \x01(\t\"\x98\x01\n\x08\x41\x63tLayer\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06inputs\x18\x02 \x03(\t\x12\x0f\n\x07outputs\x18\x03 \x03(\t\x12\x1c\n\nlayer_mode\x18\x04 \x01(\x0e\x32\x08.ActMode\x12(\n\x0clayer_params\x18\x05 \x01(\x0b\x32\x12.activation_params\x12\x15\n\rlayer_builder\x18\x06 \x01(\t*\xf2\x01\n\x07\x41\x63tMode\x12\x07\n\x03\x45LU\x10\x00\x12\x0e\n\nHARDSHRINK\x10\x01\x12\x0c\n\x08HARDTANH\x10\x02\x12\r\n\tLEAKYRELU\x10\x03\x12\x0e\n\nLOGSIGMOID\x10\x04\x12\t\n\x05PRELU\x10\x05\x12\x08\n\x04RELU\x10\x06\x12\t\n\x05RELU6\x10\x07\x12\t\n\x05RRELU\x10\x08\x12\x08\n\x04SELU\x10\t\x12\x08\n\x04\x43\x45LU\x10\n\x12\x0b\n\x07SIGMOID\x10\x0b\x12\x0c\n\x08SOFTPLUS\x10\x0c\x12\x0f\n\x0bSOFTSHRINGK\x10\r\x12\x0c\n\x08SOFTSIGN\x10\x0e\x12\x08\n\x04TANH\x10\x0f\x12\x0e\n\nTANHSHRINK\x10\x10\x12\x0e\n\nTHRESHHOLD\x10\x11')
)

_ACTMODE = _descriptor.EnumDescriptor(
  name='ActMode',
  full_name='ActMode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ELU', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HARDSHRINK', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HARDTANH', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LEAKYRELU', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LOGSIGMOID', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PRELU', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RELU', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RELU6', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RRELU', index=8, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SELU', index=9, number=9,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CELU', index=10, number=10,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SIGMOID', index=11, number=11,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SOFTPLUS', index=12, number=12,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SOFTSHRINGK', index=13, number=13,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SOFTSIGN', index=14, number=14,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TANH', index=15, number=15,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TANHSHRINK', index=16, number=16,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='THRESHHOLD', index=17, number=17,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=441,
  serialized_end=683,
)
_sym_db.RegisterEnumDescriptor(_ACTMODE)

ActMode = enum_type_wrapper.EnumTypeWrapper(_ACTMODE)
ELU = 0
HARDSHRINK = 1
HARDTANH = 2
LEAKYRELU = 3
LOGSIGMOID = 4
PRELU = 5
RELU = 6
RELU6 = 7
RRELU = 8
SELU = 9
CELU = 10
SIGMOID = 11
SOFTPLUS = 12
SOFTSHRINGK = 13
SOFTSIGN = 14
TANH = 15
TANHSHRINK = 16
THRESHHOLD = 17



_ACTIVATION_PARAMS = _descriptor.Descriptor(
  name='activation_params',
  full_name='activation_params',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='inplace', full_name='activation_params.inplace', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='alpha', full_name='activation_params.alpha', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lambd', full_name='activation_params.lambd', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_parameters', full_name='activation_params.num_parameters', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='min_val', full_name='activation_params.min_val', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_val', full_name='activation_params.max_val', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='negative_slope', full_name='activation_params.negative_slope', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lower', full_name='activation_params.lower', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='upper', full_name='activation_params.upper', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='beta', full_name='activation_params.beta', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='threshold', full_name='activation_params.threshold', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='activation_params.value', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='init', full_name='activation_params.init', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=283,
)


_ACTLAYER = _descriptor.Descriptor(
  name='ActLayer',
  full_name='ActLayer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ActLayer.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='inputs', full_name='ActLayer.inputs', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='outputs', full_name='ActLayer.outputs', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='layer_mode', full_name='ActLayer.layer_mode', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='layer_params', full_name='ActLayer.layer_params', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='layer_builder', full_name='ActLayer.layer_builder', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=286,
  serialized_end=438,
)

_ACTLAYER.fields_by_name['layer_mode'].enum_type = _ACTMODE
_ACTLAYER.fields_by_name['layer_params'].message_type = _ACTIVATION_PARAMS
DESCRIPTOR.message_types_by_name['activation_params'] = _ACTIVATION_PARAMS
DESCRIPTOR.message_types_by_name['ActLayer'] = _ACTLAYER
DESCRIPTOR.enum_types_by_name['ActMode'] = _ACTMODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

activation_params = _reflection.GeneratedProtocolMessageType('activation_params', (_message.Message,), dict(
  DESCRIPTOR = _ACTIVATION_PARAMS,
  __module__ = 'vulkan.protos.layers.activations_pb2'
  # @@protoc_insertion_point(class_scope:activation_params)
  ))
_sym_db.RegisterMessage(activation_params)

ActLayer = _reflection.GeneratedProtocolMessageType('ActLayer', (_message.Message,), dict(
  DESCRIPTOR = _ACTLAYER,
  __module__ = 'vulkan.protos.layers.activations_pb2'
  # @@protoc_insertion_point(class_scope:ActLayer)
  ))
_sym_db.RegisterMessage(ActLayer)


# @@protoc_insertion_point(module_scope)
