# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vulkan/protos/layers/conv.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='vulkan/protos/layers/conv.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x1fvulkan/protos/layers/conv.proto\"\xa1\x01\n\x0e\x63onv_parameter\x12\x13\n\x0bin_channels\x18\x01 \x01(\t\x12\x14\n\x0cout_channels\x18\x02 \x01(\t\x12\x13\n\x0bkernel_size\x18\x03 \x03(\t\x12\x0e\n\x06stride\x18\x04 \x03(\t\x12\x0f\n\x07padding\x18\x05 \x03(\t\x12\x10\n\x08\x64ilation\x18\x06 \x03(\t\x12\x0e\n\x06groups\x18\x07 \x01(\t\x12\x0c\n\x04\x62ias\x18\x08 \x01(\t\"\x97\x01\n\tConvLayer\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06inputs\x18\x02 \x03(\t\x12\x0f\n\x07outputs\x18\x03 \x03(\t\x12\x1d\n\nlayer_mode\x18\x04 \x01(\x0e\x32\t.ConvMode\x12%\n\x0clayer_params\x18\x05 \x01(\x0b\x32\x0f.conv_parameter\x12\x15\n\rlayer_builder\x18\x06 \x01(\t*a\n\x08\x43onvMode\x12\n\n\x06\x43ONV1D\x10\x00\x12\n\n\x06\x43ONV2D\x10\x01\x12\n\n\x06\x43ONV3D\x10\x02\x12\x0f\n\x0bTRANSCONV1D\x10\x03\x12\x0f\n\x0bTRANSCONV2D\x10\x04\x12\x0f\n\x0bTRANSCONV3D\x10\x05')
)

_CONVMODE = _descriptor.EnumDescriptor(
  name='ConvMode',
  full_name='ConvMode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CONV1D', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONV2D', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONV3D', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRANSCONV1D', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRANSCONV2D', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRANSCONV3D', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=353,
  serialized_end=450,
)
_sym_db.RegisterEnumDescriptor(_CONVMODE)

ConvMode = enum_type_wrapper.EnumTypeWrapper(_CONVMODE)
CONV1D = 0
CONV2D = 1
CONV3D = 2
TRANSCONV1D = 3
TRANSCONV2D = 4
TRANSCONV3D = 5



_CONV_PARAMETER = _descriptor.Descriptor(
  name='conv_parameter',
  full_name='conv_parameter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='in_channels', full_name='conv_parameter.in_channels', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='out_channels', full_name='conv_parameter.out_channels', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kernel_size', full_name='conv_parameter.kernel_size', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stride', full_name='conv_parameter.stride', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='padding', full_name='conv_parameter.padding', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dilation', full_name='conv_parameter.dilation', index=5,
      number=6, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='groups', full_name='conv_parameter.groups', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bias', full_name='conv_parameter.bias', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=197,
)


_CONVLAYER = _descriptor.Descriptor(
  name='ConvLayer',
  full_name='ConvLayer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ConvLayer.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='inputs', full_name='ConvLayer.inputs', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='outputs', full_name='ConvLayer.outputs', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='layer_mode', full_name='ConvLayer.layer_mode', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='layer_params', full_name='ConvLayer.layer_params', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='layer_builder', full_name='ConvLayer.layer_builder', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=200,
  serialized_end=351,
)

_CONVLAYER.fields_by_name['layer_mode'].enum_type = _CONVMODE
_CONVLAYER.fields_by_name['layer_params'].message_type = _CONV_PARAMETER
DESCRIPTOR.message_types_by_name['conv_parameter'] = _CONV_PARAMETER
DESCRIPTOR.message_types_by_name['ConvLayer'] = _CONVLAYER
DESCRIPTOR.enum_types_by_name['ConvMode'] = _CONVMODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

conv_parameter = _reflection.GeneratedProtocolMessageType('conv_parameter', (_message.Message,), dict(
  DESCRIPTOR = _CONV_PARAMETER,
  __module__ = 'vulkan.protos.layers.conv_pb2'
  # @@protoc_insertion_point(class_scope:conv_parameter)
  ))
_sym_db.RegisterMessage(conv_parameter)

ConvLayer = _reflection.GeneratedProtocolMessageType('ConvLayer', (_message.Message,), dict(
  DESCRIPTOR = _CONVLAYER,
  __module__ = 'vulkan.protos.layers.conv_pb2'
  # @@protoc_insertion_point(class_scope:ConvLayer)
  ))
_sym_db.RegisterMessage(ConvLayer)


# @@protoc_insertion_point(module_scope)
