# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vulkan/protos/layers/pooling.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='vulkan/protos/layers/pooling.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\"vulkan/protos/layers/pooling.proto\"\xf8\x01\n\x11pooling_parameter\x12\x13\n\x0bkernel_size\x18\x01 \x03(\t\x12\x0e\n\x06stride\x18\x02 \x03(\t\x12\x0f\n\x07padding\x18\x03 \x03(\t\x12\x10\n\x08\x64ilation\x18\x04 \x03(\t\x12\x16\n\x0ereturn_indices\x18\x05 \x01(\t\x12\x11\n\tceil_mode\x18\x06 \x01(\t\x12\x19\n\x11\x63ount_include_pad\x18\x07 \x01(\t\x12\x13\n\x0boutput_size\x18\x08 \x03(\t\x12\x11\n\tnorm_type\x18\t \x01(\t\x12\x14\n\x0coutput_ratio\x18\n \x01(\t\x12\x17\n\x0f_random_samples\x18\x0b \x01(\t\"\x9a\x01\n\tPoolLayer\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06inputs\x18\x02 \x03(\t\x12\x0f\n\x07outputs\x18\x03 \x03(\t\x12\x1d\n\nlayer_mode\x18\x04 \x01(\x0e\x32\t.PoolMode\x12(\n\x0clayer_params\x18\x05 \x01(\x0b\x32\x12.pooling_parameter\x12\x15\n\rlayer_builder\x18\x06 \x01(\t*\xd6\x02\n\x08PoolMode\x12\r\n\tMAXPOOL1D\x10\x00\x12\r\n\tMAXPOOL2D\x10\x01\x12\r\n\tMAXPOOL3D\x10\x02\x12\r\n\tAVGPOOL1D\x10\x03\x12\r\n\tAVGPOOL2D\x10\x04\x12\r\n\tAVGPOOL3D\x10\x05\x12\x15\n\x11\x41\x44\x41PTIVEMAXPOOL1D\x10\x06\x12\x15\n\x11\x41\x44\x41PTIVEMAXPOOL2D\x10\x07\x12\x15\n\x11\x41\x44\x41PTIVEMAXPOOL3D\x10\t\x12\x15\n\x11\x41\x44\x41PTIVEAVGPOOL1D\x10\n\x12\x15\n\x11\x41\x44\x41PTIVEAVGPOOL2D\x10\x0b\x12\x15\n\x11\x41\x44\x41PTIVEAVGPOOL3D\x10\x0c\x12\x0f\n\x0bMAXUNPOOL1D\x10\r\x12\x0f\n\x0bMAXUNPOOL2D\x10\x0e\x12\x0f\n\x0bMAXUNPOOL3D\x10\x0f\x12\x17\n\x13\x46RACTIONALMAXPOOL2D\x10\x10\x12\x0c\n\x08LPPOOL1D\x10\x11\x12\x0c\n\x08LPPOOL2D\x10\x12')
)

_POOLMODE = _descriptor.EnumDescriptor(
  name='PoolMode',
  full_name='PoolMode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MAXPOOL1D', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MAXPOOL2D', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MAXPOOL3D', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AVGPOOL1D', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AVGPOOL2D', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AVGPOOL3D', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ADAPTIVEMAXPOOL1D', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ADAPTIVEMAXPOOL2D', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ADAPTIVEMAXPOOL3D', index=8, number=9,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ADAPTIVEAVGPOOL1D', index=9, number=10,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ADAPTIVEAVGPOOL2D', index=10, number=11,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ADAPTIVEAVGPOOL3D', index=11, number=12,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MAXUNPOOL1D', index=12, number=13,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MAXUNPOOL2D', index=13, number=14,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MAXUNPOOL3D', index=14, number=15,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FRACTIONALMAXPOOL2D', index=15, number=16,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LPPOOL1D', index=16, number=17,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LPPOOL2D', index=17, number=18,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=447,
  serialized_end=789,
)
_sym_db.RegisterEnumDescriptor(_POOLMODE)

PoolMode = enum_type_wrapper.EnumTypeWrapper(_POOLMODE)
MAXPOOL1D = 0
MAXPOOL2D = 1
MAXPOOL3D = 2
AVGPOOL1D = 3
AVGPOOL2D = 4
AVGPOOL3D = 5
ADAPTIVEMAXPOOL1D = 6
ADAPTIVEMAXPOOL2D = 7
ADAPTIVEMAXPOOL3D = 9
ADAPTIVEAVGPOOL1D = 10
ADAPTIVEAVGPOOL2D = 11
ADAPTIVEAVGPOOL3D = 12
MAXUNPOOL1D = 13
MAXUNPOOL2D = 14
MAXUNPOOL3D = 15
FRACTIONALMAXPOOL2D = 16
LPPOOL1D = 17
LPPOOL2D = 18



_POOLING_PARAMETER = _descriptor.Descriptor(
  name='pooling_parameter',
  full_name='pooling_parameter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='kernel_size', full_name='pooling_parameter.kernel_size', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stride', full_name='pooling_parameter.stride', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='padding', full_name='pooling_parameter.padding', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dilation', full_name='pooling_parameter.dilation', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='return_indices', full_name='pooling_parameter.return_indices', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ceil_mode', full_name='pooling_parameter.ceil_mode', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='count_include_pad', full_name='pooling_parameter.count_include_pad', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='output_size', full_name='pooling_parameter.output_size', index=7,
      number=8, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='norm_type', full_name='pooling_parameter.norm_type', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='output_ratio', full_name='pooling_parameter.output_ratio', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='_random_samples', full_name='pooling_parameter._random_samples', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=287,
)


_POOLLAYER = _descriptor.Descriptor(
  name='PoolLayer',
  full_name='PoolLayer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='PoolLayer.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='inputs', full_name='PoolLayer.inputs', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='outputs', full_name='PoolLayer.outputs', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='layer_mode', full_name='PoolLayer.layer_mode', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='layer_params', full_name='PoolLayer.layer_params', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='layer_builder', full_name='PoolLayer.layer_builder', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=290,
  serialized_end=444,
)

_POOLLAYER.fields_by_name['layer_mode'].enum_type = _POOLMODE
_POOLLAYER.fields_by_name['layer_params'].message_type = _POOLING_PARAMETER
DESCRIPTOR.message_types_by_name['pooling_parameter'] = _POOLING_PARAMETER
DESCRIPTOR.message_types_by_name['PoolLayer'] = _POOLLAYER
DESCRIPTOR.enum_types_by_name['PoolMode'] = _POOLMODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

pooling_parameter = _reflection.GeneratedProtocolMessageType('pooling_parameter', (_message.Message,), dict(
  DESCRIPTOR = _POOLING_PARAMETER,
  __module__ = 'vulkan.protos.layers.pooling_pb2'
  # @@protoc_insertion_point(class_scope:pooling_parameter)
  ))
_sym_db.RegisterMessage(pooling_parameter)

PoolLayer = _reflection.GeneratedProtocolMessageType('PoolLayer', (_message.Message,), dict(
  DESCRIPTOR = _POOLLAYER,
  __module__ = 'vulkan.protos.layers.pooling_pb2'
  # @@protoc_insertion_point(class_scope:PoolLayer)
  ))
_sym_db.RegisterMessage(PoolLayer)


# @@protoc_insertion_point(module_scope)
