# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vulkan/protos/blocks/blocks.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from vulkan.protos.layers import layers_pb2 as vulkan_dot_protos_dot_layers_dot_layers__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='vulkan/protos/blocks/blocks.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n!vulkan/protos/blocks/blocks.proto\x1a!vulkan/protos/layers/layers.proto\"M\n\x06\x42locks\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x1e\n\nblock_mode\x18\x02 \x01(\x0e\x32\n.BlockMode\x12\x15\n\x05layer\x18\x03 \x03(\x0b\x32\x06.Layer*D\n\tBlockMode\x12\r\n\tRES_BASIC\x10\x00\x12\x12\n\x0eRES_BOTTLENECK\x10\x01\x12\x14\n\x10\x44\x45NSE_BOTTLENECK\x10\x02')
  ,
  dependencies=[vulkan_dot_protos_dot_layers_dot_layers__pb2.DESCRIPTOR,])

_BLOCKMODE = _descriptor.EnumDescriptor(
  name='BlockMode',
  full_name='BlockMode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RES_BASIC', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RES_BOTTLENECK', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DENSE_BOTTLENECK', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=151,
  serialized_end=219,
)
_sym_db.RegisterEnumDescriptor(_BLOCKMODE)

BlockMode = enum_type_wrapper.EnumTypeWrapper(_BLOCKMODE)
RES_BASIC = 0
RES_BOTTLENECK = 1
DENSE_BOTTLENECK = 2



_BLOCKS = _descriptor.Descriptor(
  name='Blocks',
  full_name='Blocks',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Blocks.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='block_mode', full_name='Blocks.block_mode', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='layer', full_name='Blocks.layer', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=149,
)

_BLOCKS.fields_by_name['block_mode'].enum_type = _BLOCKMODE
_BLOCKS.fields_by_name['layer'].message_type = vulkan_dot_protos_dot_layers_dot_layers__pb2._LAYER
DESCRIPTOR.message_types_by_name['Blocks'] = _BLOCKS
DESCRIPTOR.enum_types_by_name['BlockMode'] = _BLOCKMODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Blocks = _reflection.GeneratedProtocolMessageType('Blocks', (_message.Message,), dict(
  DESCRIPTOR = _BLOCKS,
  __module__ = 'vulkan.protos.blocks.blocks_pb2'
  # @@protoc_insertion_point(class_scope:Blocks)
  ))
_sym_db.RegisterMessage(Blocks)


# @@protoc_insertion_point(module_scope)
