# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vulkan/protos/layers/layers.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from vulkan.protos.layers import conv_pb2 as vulkan_dot_protos_dot_layers_dot_conv__pb2
from vulkan.protos.layers import pooling_pb2 as vulkan_dot_protos_dot_layers_dot_pooling__pb2
from vulkan.protos.layers import linear_pb2 as vulkan_dot_protos_dot_layers_dot_linear__pb2
from vulkan.protos.layers import dropout_pb2 as vulkan_dot_protos_dot_layers_dot_dropout__pb2
from vulkan.protos.layers import activations_pb2 as vulkan_dot_protos_dot_layers_dot_activations__pb2
from vulkan.protos.layers import basefunc_pb2 as vulkan_dot_protos_dot_layers_dot_basefunc__pb2
from vulkan.protos.layers import vulkan_pb2 as vulkan_dot_protos_dot_layers_dot_vulkan__pb2
from vulkan.protos.layers import norm_pb2 as vulkan_dot_protos_dot_layers_dot_norm__pb2
from vulkan.protos.layers import padding_pb2 as vulkan_dot_protos_dot_layers_dot_padding__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='vulkan/protos/layers/layers.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n!vulkan/protos/layers/layers.proto\x1a\x1fvulkan/protos/layers/conv.proto\x1a\"vulkan/protos/layers/pooling.proto\x1a!vulkan/protos/layers/linear.proto\x1a\"vulkan/protos/layers/dropout.proto\x1a&vulkan/protos/layers/activations.proto\x1a#vulkan/protos/layers/basefunc.proto\x1a!vulkan/protos/layers/vulkan.proto\x1a\x1fvulkan/protos/layers/norm.proto\x1a\"vulkan/protos/layers/padding.proto\"\xac\x02\n\x05Layer\x12\x1a\n\x04\x63onv\x18\x01 \x01(\x0b\x32\n.ConvLayerH\x00\x12\x1a\n\x04pool\x18\x02 \x01(\x0b\x32\n.PoolLayerH\x00\x12\x1e\n\x06linear\x18\x03 \x01(\x0b\x32\x0c.LinearLayerH\x00\x12 \n\x07\x64ropout\x18\x04 \x01(\x0b\x32\r.DropoutLayerH\x00\x12\x18\n\x03\x61\x63t\x18\x05 \x01(\x0b\x32\t.ActLayerH\x00\x12\"\n\x08\x62\x61sefunc\x18\x06 \x01(\x0b\x32\x0e.BaseFuncLayerH\x00\x12\x1e\n\x06vulkan\x18\x07 \x01(\x0b\x32\x0c.VulkanLayerH\x00\x12\x1a\n\x04norm\x18\x08 \x01(\x0b\x32\n.NormLayerH\x00\x12 \n\x07padding\x18\t \x01(\x0b\x32\r.PaddingLayerH\x00\x42\r\n\x0blayer_oneof')
  ,
  dependencies=[vulkan_dot_protos_dot_layers_dot_conv__pb2.DESCRIPTOR,vulkan_dot_protos_dot_layers_dot_pooling__pb2.DESCRIPTOR,vulkan_dot_protos_dot_layers_dot_linear__pb2.DESCRIPTOR,vulkan_dot_protos_dot_layers_dot_dropout__pb2.DESCRIPTOR,vulkan_dot_protos_dot_layers_dot_activations__pb2.DESCRIPTOR,vulkan_dot_protos_dot_layers_dot_basefunc__pb2.DESCRIPTOR,vulkan_dot_protos_dot_layers_dot_vulkan__pb2.DESCRIPTOR,vulkan_dot_protos_dot_layers_dot_norm__pb2.DESCRIPTOR,vulkan_dot_protos_dot_layers_dot_padding__pb2.DESCRIPTOR,])




_LAYER = _descriptor.Descriptor(
  name='Layer',
  full_name='Layer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='conv', full_name='Layer.conv', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pool', full_name='Layer.pool', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='linear', full_name='Layer.linear', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dropout', full_name='Layer.dropout', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='act', full_name='Layer.act', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='basefunc', full_name='Layer.basefunc', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vulkan', full_name='Layer.vulkan', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='norm', full_name='Layer.norm', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='padding', full_name='Layer.padding', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='layer_oneof', full_name='Layer.layer_oneof',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=359,
  serialized_end=659,
)

_LAYER.fields_by_name['conv'].message_type = vulkan_dot_protos_dot_layers_dot_conv__pb2._CONVLAYER
_LAYER.fields_by_name['pool'].message_type = vulkan_dot_protos_dot_layers_dot_pooling__pb2._POOLLAYER
_LAYER.fields_by_name['linear'].message_type = vulkan_dot_protos_dot_layers_dot_linear__pb2._LINEARLAYER
_LAYER.fields_by_name['dropout'].message_type = vulkan_dot_protos_dot_layers_dot_dropout__pb2._DROPOUTLAYER
_LAYER.fields_by_name['act'].message_type = vulkan_dot_protos_dot_layers_dot_activations__pb2._ACTLAYER
_LAYER.fields_by_name['basefunc'].message_type = vulkan_dot_protos_dot_layers_dot_basefunc__pb2._BASEFUNCLAYER
_LAYER.fields_by_name['vulkan'].message_type = vulkan_dot_protos_dot_layers_dot_vulkan__pb2._VULKANLAYER
_LAYER.fields_by_name['norm'].message_type = vulkan_dot_protos_dot_layers_dot_norm__pb2._NORMLAYER
_LAYER.fields_by_name['padding'].message_type = vulkan_dot_protos_dot_layers_dot_padding__pb2._PADDINGLAYER
_LAYER.oneofs_by_name['layer_oneof'].fields.append(
  _LAYER.fields_by_name['conv'])
_LAYER.fields_by_name['conv'].containing_oneof = _LAYER.oneofs_by_name['layer_oneof']
_LAYER.oneofs_by_name['layer_oneof'].fields.append(
  _LAYER.fields_by_name['pool'])
_LAYER.fields_by_name['pool'].containing_oneof = _LAYER.oneofs_by_name['layer_oneof']
_LAYER.oneofs_by_name['layer_oneof'].fields.append(
  _LAYER.fields_by_name['linear'])
_LAYER.fields_by_name['linear'].containing_oneof = _LAYER.oneofs_by_name['layer_oneof']
_LAYER.oneofs_by_name['layer_oneof'].fields.append(
  _LAYER.fields_by_name['dropout'])
_LAYER.fields_by_name['dropout'].containing_oneof = _LAYER.oneofs_by_name['layer_oneof']
_LAYER.oneofs_by_name['layer_oneof'].fields.append(
  _LAYER.fields_by_name['act'])
_LAYER.fields_by_name['act'].containing_oneof = _LAYER.oneofs_by_name['layer_oneof']
_LAYER.oneofs_by_name['layer_oneof'].fields.append(
  _LAYER.fields_by_name['basefunc'])
_LAYER.fields_by_name['basefunc'].containing_oneof = _LAYER.oneofs_by_name['layer_oneof']
_LAYER.oneofs_by_name['layer_oneof'].fields.append(
  _LAYER.fields_by_name['vulkan'])
_LAYER.fields_by_name['vulkan'].containing_oneof = _LAYER.oneofs_by_name['layer_oneof']
_LAYER.oneofs_by_name['layer_oneof'].fields.append(
  _LAYER.fields_by_name['norm'])
_LAYER.fields_by_name['norm'].containing_oneof = _LAYER.oneofs_by_name['layer_oneof']
_LAYER.oneofs_by_name['layer_oneof'].fields.append(
  _LAYER.fields_by_name['padding'])
_LAYER.fields_by_name['padding'].containing_oneof = _LAYER.oneofs_by_name['layer_oneof']
DESCRIPTOR.message_types_by_name['Layer'] = _LAYER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Layer = _reflection.GeneratedProtocolMessageType('Layer', (_message.Message,), dict(
  DESCRIPTOR = _LAYER,
  __module__ = 'vulkan.protos.layers.layers_pb2'
  # @@protoc_insertion_point(class_scope:Layer)
  ))
_sym_db.RegisterMessage(Layer)


# @@protoc_insertion_point(module_scope)
