# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vulkan/protos/layers/norm.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='vulkan/protos/layers/norm.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x1fvulkan/protos/layers/norm.proto\"\x89\x02\n\x0fNorm_Parameters\x12\x14\n\x0cnum_features\x18\x01 \x01(\t\x12\x0b\n\x03\x65ps\x18\x02 \x01(\t\x12\x10\n\x08momentum\x18\x03 \x01(\t\x12\x0e\n\x06\x61\x66\x66ine\x18\x04 \x01(\t\x12\x1b\n\x13track_running_stats\x18\x05 \x01(\t\x12\x18\n\x10normalized_shape\x18\x06 \x03(\t\x12\x1a\n\x12\x65lementwise_affine\x18\x07 \x01(\t\x12\x0c\n\x04size\x18\x08 \x01(\t\x12\r\n\x05\x61lpha\x18\t \x01(\t\x12\x0c\n\x04\x62\x65ta\x18\n \x01(\t\x12\t\n\x01k\x18\x0b \x01(\t\x12\x12\n\nnum_groups\x18\x0c \x01(\t\x12\x14\n\x0cnum_channels\x18\r \x01(\t\"\x98\x01\n\tNormLayer\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06inputs\x18\x02 \x03(\t\x12\x0f\n\x07outputs\x18\x03 \x03(\t\x12\x1d\n\nlayer_mode\x18\x04 \x01(\x0e\x32\t.NormMode\x12&\n\x0clayer_params\x18\x05 \x01(\x0b\x32\x10.Norm_Parameters\x12\x15\n\rlayer_builder\x18\x06 \x01(\t*\xae\x01\n\x08NormMode\x12\x0f\n\x0b\x42\x41TCHNORM1D\x10\x00\x12\x0f\n\x0b\x42\x41TCHNORM2D\x10\x01\x12\x0f\n\x0b\x42\x41TCHNORM3D\x10\x02\x12\r\n\tGROUPNORM\x10\x03\x12\x12\n\x0eINSTANCENORM1D\x10\x04\x12\x12\n\x0eINSTANCENORM2D\x10\x05\x12\x12\n\x0eINSTANCENORM3D\x10\x06\x12\r\n\tLAYERNORM\x10\x07\x12\x15\n\x11LOCALRESPONSENORM\x10\x08')
)

_NORMMODE = _descriptor.EnumDescriptor(
  name='NormMode',
  full_name='NormMode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BATCHNORM1D', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BATCHNORM2D', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BATCHNORM3D', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GROUPNORM', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INSTANCENORM1D', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INSTANCENORM2D', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INSTANCENORM3D', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LAYERNORM', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LOCALRESPONSENORM', index=8, number=8,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=459,
  serialized_end=633,
)
_sym_db.RegisterEnumDescriptor(_NORMMODE)

NormMode = enum_type_wrapper.EnumTypeWrapper(_NORMMODE)
BATCHNORM1D = 0
BATCHNORM2D = 1
BATCHNORM3D = 2
GROUPNORM = 3
INSTANCENORM1D = 4
INSTANCENORM2D = 5
INSTANCENORM3D = 6
LAYERNORM = 7
LOCALRESPONSENORM = 8



_NORM_PARAMETERS = _descriptor.Descriptor(
  name='Norm_Parameters',
  full_name='Norm_Parameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_features', full_name='Norm_Parameters.num_features', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='eps', full_name='Norm_Parameters.eps', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='momentum', full_name='Norm_Parameters.momentum', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='affine', full_name='Norm_Parameters.affine', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='track_running_stats', full_name='Norm_Parameters.track_running_stats', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='normalized_shape', full_name='Norm_Parameters.normalized_shape', index=5,
      number=6, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='elementwise_affine', full_name='Norm_Parameters.elementwise_affine', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='size', full_name='Norm_Parameters.size', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='alpha', full_name='Norm_Parameters.alpha', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='beta', full_name='Norm_Parameters.beta', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='k', full_name='Norm_Parameters.k', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_groups', full_name='Norm_Parameters.num_groups', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_channels', full_name='Norm_Parameters.num_channels', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=301,
)


_NORMLAYER = _descriptor.Descriptor(
  name='NormLayer',
  full_name='NormLayer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='NormLayer.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='inputs', full_name='NormLayer.inputs', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='outputs', full_name='NormLayer.outputs', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='layer_mode', full_name='NormLayer.layer_mode', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='layer_params', full_name='NormLayer.layer_params', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='layer_builder', full_name='NormLayer.layer_builder', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=304,
  serialized_end=456,
)

_NORMLAYER.fields_by_name['layer_mode'].enum_type = _NORMMODE
_NORMLAYER.fields_by_name['layer_params'].message_type = _NORM_PARAMETERS
DESCRIPTOR.message_types_by_name['Norm_Parameters'] = _NORM_PARAMETERS
DESCRIPTOR.message_types_by_name['NormLayer'] = _NORMLAYER
DESCRIPTOR.enum_types_by_name['NormMode'] = _NORMMODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Norm_Parameters = _reflection.GeneratedProtocolMessageType('Norm_Parameters', (_message.Message,), dict(
  DESCRIPTOR = _NORM_PARAMETERS,
  __module__ = 'vulkan.protos.layers.norm_pb2'
  # @@protoc_insertion_point(class_scope:Norm_Parameters)
  ))
_sym_db.RegisterMessage(Norm_Parameters)

NormLayer = _reflection.GeneratedProtocolMessageType('NormLayer', (_message.Message,), dict(
  DESCRIPTOR = _NORMLAYER,
  __module__ = 'vulkan.protos.layers.norm_pb2'
  # @@protoc_insertion_point(class_scope:NormLayer)
  ))
_sym_db.RegisterMessage(NormLayer)


# @@protoc_insertion_point(module_scope)
