# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vulkan/protos/layers/padding.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='vulkan/protos/layers/padding.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\"vulkan/protos/layers/padding.proto\"0\n\x0epadding_params\x12\x0f\n\x07padding\x18\x01 \x03(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\x99\x01\n\x0cPaddingLayer\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06inputs\x18\x02 \x03(\t\x12\x0f\n\x07outputs\x18\x03 \x03(\t\x12\x1c\n\nlayer_mode\x18\x04 \x01(\x0e\x32\x08.PadMode\x12%\n\x0clayer_params\x18\x05 \x01(\x0b\x32\x0f.padding_params\x12\x15\n\rlayer_builder\x18\x06 \x01(\t*\xbd\x01\n\x07PadMode\x12\x13\n\x0fREFLECTIONPAD1D\x10\x00\x12\x13\n\x0fREFLECTIONPAD2D\x10\x01\x12\x14\n\x10REPLICATIONPAD1D\x10\x02\x12\x14\n\x10REPLICATIONPAD2D\x10\x03\x12\x14\n\x10REPLICATIONPAD3D\x10\x04\x12\r\n\tZEROPAD2D\x10\x05\x12\x11\n\rCONSTANTPAD1D\x10\x06\x12\x11\n\rCONSTANTPAD2D\x10\x07\x12\x11\n\rCONSTANTPAD3D\x10\x08')
)

_PADMODE = _descriptor.EnumDescriptor(
  name='PadMode',
  full_name='PadMode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='REFLECTIONPAD1D', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REFLECTIONPAD2D', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REPLICATIONPAD1D', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REPLICATIONPAD2D', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REPLICATIONPAD3D', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ZEROPAD2D', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONSTANTPAD1D', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONSTANTPAD2D', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONSTANTPAD3D', index=8, number=8,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=245,
  serialized_end=434,
)
_sym_db.RegisterEnumDescriptor(_PADMODE)

PadMode = enum_type_wrapper.EnumTypeWrapper(_PADMODE)
REFLECTIONPAD1D = 0
REFLECTIONPAD2D = 1
REPLICATIONPAD1D = 2
REPLICATIONPAD2D = 3
REPLICATIONPAD3D = 4
ZEROPAD2D = 5
CONSTANTPAD1D = 6
CONSTANTPAD2D = 7
CONSTANTPAD3D = 8



_PADDING_PARAMS = _descriptor.Descriptor(
  name='padding_params',
  full_name='padding_params',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='padding', full_name='padding_params.padding', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='padding_params.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=86,
)


_PADDINGLAYER = _descriptor.Descriptor(
  name='PaddingLayer',
  full_name='PaddingLayer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='PaddingLayer.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='inputs', full_name='PaddingLayer.inputs', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='outputs', full_name='PaddingLayer.outputs', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='layer_mode', full_name='PaddingLayer.layer_mode', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='layer_params', full_name='PaddingLayer.layer_params', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='layer_builder', full_name='PaddingLayer.layer_builder', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=242,
)

_PADDINGLAYER.fields_by_name['layer_mode'].enum_type = _PADMODE
_PADDINGLAYER.fields_by_name['layer_params'].message_type = _PADDING_PARAMS
DESCRIPTOR.message_types_by_name['padding_params'] = _PADDING_PARAMS
DESCRIPTOR.message_types_by_name['PaddingLayer'] = _PADDINGLAYER
DESCRIPTOR.enum_types_by_name['PadMode'] = _PADMODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

padding_params = _reflection.GeneratedProtocolMessageType('padding_params', (_message.Message,), dict(
  DESCRIPTOR = _PADDING_PARAMS,
  __module__ = 'vulkan.protos.layers.padding_pb2'
  # @@protoc_insertion_point(class_scope:padding_params)
  ))
_sym_db.RegisterMessage(padding_params)

PaddingLayer = _reflection.GeneratedProtocolMessageType('PaddingLayer', (_message.Message,), dict(
  DESCRIPTOR = _PADDINGLAYER,
  __module__ = 'vulkan.protos.layers.padding_pb2'
  # @@protoc_insertion_point(class_scope:PaddingLayer)
  ))
_sym_db.RegisterMessage(PaddingLayer)


# @@protoc_insertion_point(module_scope)
