# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vulkan/protos/layers/vulkan.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='vulkan/protos/layers/vulkan.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n!vulkan/protos/layers/vulkan.proto\"M\n\x11Vulkan_Parameters\x12\x14\n\x0ctarget_shape\x18\x01 \x03(\t\x12\x11\n\tstart_dim\x18\x02 \x01(\t\x12\x0f\n\x07\x65nd_dim\x18\x03 \x01(\t\"\x9e\x01\n\x0bVulkanLayer\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06inputs\x18\x02 \x03(\t\x12\x0f\n\x07outputs\x18\x03 \x03(\t\x12\x1f\n\nlayer_mode\x18\x04 \x01(\x0e\x32\x0b.VulkanMode\x12(\n\x0clayer_params\x18\x05 \x01(\x0b\x32\x12.Vulkan_Parameters\x12\x15\n\rlayer_builder\x18\x06 \x01(\t*&\n\nVulkanMode\x12\x0b\n\x07RESHAPE\x10\x00\x12\x0b\n\x07\x46LATTEN\x10\x01')
)

_VULKANMODE = _descriptor.EnumDescriptor(
  name='VulkanMode',
  full_name='VulkanMode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RESHAPE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FLATTEN', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=277,
  serialized_end=315,
)
_sym_db.RegisterEnumDescriptor(_VULKANMODE)

VulkanMode = enum_type_wrapper.EnumTypeWrapper(_VULKANMODE)
RESHAPE = 0
FLATTEN = 1



_VULKAN_PARAMETERS = _descriptor.Descriptor(
  name='Vulkan_Parameters',
  full_name='Vulkan_Parameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='target_shape', full_name='Vulkan_Parameters.target_shape', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start_dim', full_name='Vulkan_Parameters.start_dim', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end_dim', full_name='Vulkan_Parameters.end_dim', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=114,
)


_VULKANLAYER = _descriptor.Descriptor(
  name='VulkanLayer',
  full_name='VulkanLayer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='VulkanLayer.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='inputs', full_name='VulkanLayer.inputs', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='outputs', full_name='VulkanLayer.outputs', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='layer_mode', full_name='VulkanLayer.layer_mode', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='layer_params', full_name='VulkanLayer.layer_params', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='layer_builder', full_name='VulkanLayer.layer_builder', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=275,
)

_VULKANLAYER.fields_by_name['layer_mode'].enum_type = _VULKANMODE
_VULKANLAYER.fields_by_name['layer_params'].message_type = _VULKAN_PARAMETERS
DESCRIPTOR.message_types_by_name['Vulkan_Parameters'] = _VULKAN_PARAMETERS
DESCRIPTOR.message_types_by_name['VulkanLayer'] = _VULKANLAYER
DESCRIPTOR.enum_types_by_name['VulkanMode'] = _VULKANMODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Vulkan_Parameters = _reflection.GeneratedProtocolMessageType('Vulkan_Parameters', (_message.Message,), dict(
  DESCRIPTOR = _VULKAN_PARAMETERS,
  __module__ = 'vulkan.protos.layers.vulkan_pb2'
  # @@protoc_insertion_point(class_scope:Vulkan_Parameters)
  ))
_sym_db.RegisterMessage(Vulkan_Parameters)

VulkanLayer = _reflection.GeneratedProtocolMessageType('VulkanLayer', (_message.Message,), dict(
  DESCRIPTOR = _VULKANLAYER,
  __module__ = 'vulkan.protos.layers.vulkan_pb2'
  # @@protoc_insertion_point(class_scope:VulkanLayer)
  ))
_sym_db.RegisterMessage(VulkanLayer)


# @@protoc_insertion_point(module_scope)
