# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vulkan/protos/skeletons/skeleton.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from vulkan.protos.skeletons import plain_pb2 as vulkan_dot_protos_dot_skeletons_dot_plain__pb2
from vulkan.protos.skeletons import block_wise_pb2 as vulkan_dot_protos_dot_skeletons_dot_block__wise__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='vulkan/protos/skeletons/skeleton.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n&vulkan/protos/skeletons/skeleton.proto\x1a#vulkan/protos/skeletons/plain.proto\x1a(vulkan/protos/skeletons/block_wise.proto\"f\n\tskeletons\x12\x1e\n\tplain_net\x18\x01 \x01(\x0b\x32\t.PlainNetH\x00\x12\'\n\x0e\x62lock_wise_net\x18\x02 \x01(\x0b\x32\r.BlockWiseNetH\x00\x42\x10\n\x0eskeleton_oneof')
  ,
  dependencies=[vulkan_dot_protos_dot_skeletons_dot_plain__pb2.DESCRIPTOR,vulkan_dot_protos_dot_skeletons_dot_block__wise__pb2.DESCRIPTOR,])




_SKELETONS = _descriptor.Descriptor(
  name='skeletons',
  full_name='skeletons',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='plain_net', full_name='skeletons.plain_net', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='block_wise_net', full_name='skeletons.block_wise_net', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='skeleton_oneof', full_name='skeletons.skeleton_oneof',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=121,
  serialized_end=223,
)

_SKELETONS.fields_by_name['plain_net'].message_type = vulkan_dot_protos_dot_skeletons_dot_plain__pb2._PLAINNET
_SKELETONS.fields_by_name['block_wise_net'].message_type = vulkan_dot_protos_dot_skeletons_dot_block__wise__pb2._BLOCKWISENET
_SKELETONS.oneofs_by_name['skeleton_oneof'].fields.append(
  _SKELETONS.fields_by_name['plain_net'])
_SKELETONS.fields_by_name['plain_net'].containing_oneof = _SKELETONS.oneofs_by_name['skeleton_oneof']
_SKELETONS.oneofs_by_name['skeleton_oneof'].fields.append(
  _SKELETONS.fields_by_name['block_wise_net'])
_SKELETONS.fields_by_name['block_wise_net'].containing_oneof = _SKELETONS.oneofs_by_name['skeleton_oneof']
DESCRIPTOR.message_types_by_name['skeletons'] = _SKELETONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

skeletons = _reflection.GeneratedProtocolMessageType('skeletons', (_message.Message,), dict(
  DESCRIPTOR = _SKELETONS,
  __module__ = 'vulkan.protos.skeletons.skeleton_pb2'
  # @@protoc_insertion_point(class_scope:skeletons)
  ))
_sym_db.RegisterMessage(skeletons)


# @@protoc_insertion_point(module_scope)
