# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vulkan/protos/skeletons/plain.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from vulkan.protos.layers import layers_pb2 as vulkan_dot_protos_dot_layers_dot_layers__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='vulkan/protos/skeletons/plain.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n#vulkan/protos/skeletons/plain.proto\x1a!vulkan/protos/layers/layers.proto\"/\n\x08PlainNet\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x15\n\x05layer\x18\x02 \x03(\x0b\x32\x06.Layer')
  ,
  dependencies=[vulkan_dot_protos_dot_layers_dot_layers__pb2.DESCRIPTOR,])




_PLAINNET = _descriptor.Descriptor(
  name='PlainNet',
  full_name='PlainNet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='PlainNet.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='layer', full_name='PlainNet.layer', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=121,
)

_PLAINNET.fields_by_name['layer'].message_type = vulkan_dot_protos_dot_layers_dot_layers__pb2._LAYER
DESCRIPTOR.message_types_by_name['PlainNet'] = _PLAINNET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PlainNet = _reflection.GeneratedProtocolMessageType('PlainNet', (_message.Message,), dict(
  DESCRIPTOR = _PLAINNET,
  __module__ = 'vulkan.protos.skeletons.plain_pb2'
  # @@protoc_insertion_point(class_scope:PlainNet)
  ))
_sym_db.RegisterMessage(PlainNet)


# @@protoc_insertion_point(module_scope)
